### ISSUE TITLE
Create a community Discord

### ISSUE THREAD

**Issue by nurse-the-code** [Divine-Star-Software/DivineVoxelEngine#11]
Feature Request(?)

I apologize if this is the wrong form, but this is a really cool project and it would be awesome if there was a community Discord (or something similar). This would enable people using the engine to ask questions about how to use the engine, share their creations, etc.

**Comment by lucasdamianjohnson** [comment]
So, I was thinking about this for a little bit but yeah here is a link to one:

[https://discord.gg/e2tFazST](https://discord.gg/e2tFazST)

I have never set up a discord before and I honestly rarely use one but for the sake of this, I will keep an eye on it and do what I can.

**Comment by lucasdamianjohnson** [comment]
All right cool. 
The discord has been made. I am gonna close this issue out.
