### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by nurse-the-code** [Divine-Star-Software/DivineVoxelEngine#7]
It would be great if the documentation/wiki could be available offline.

**Comment by lucasdamianjohnson** [comment]
Hello and thank you for the issue. 
Does this work for you:
```
git clone https://github.com/Divine-Star-Software/DivineVoxelEngine.wiki.git
```
This should clone the wiki locally. 
If it does not please let me know. 

Also currently working on updating the wiki for Alpha 1.1. But the TestWorlds examples are always up to date.
